# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from node_listener.grpc import storage_pb2 as node__listener_dot_grpc_dot_storage__pb2


class ProviderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.get_storage = channel.unary_unary(
        '/Provider/get_storage',
        request_serializer=node__listener_dot_grpc_dot_storage__pb2.Request.SerializeToString,
        response_deserializer=node__listener_dot_grpc_dot_storage__pb2.Response.FromString,
        )
    self.get_changes = channel.unary_stream(
        '/Provider/get_changes',
        request_serializer=node__listener_dot_grpc_dot_storage__pb2.EmptyRequest.SerializeToString,
        response_deserializer=node__listener_dot_grpc_dot_storage__pb2.Response.FromString,
        )


class ProviderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def get_storage(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def get_changes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ProviderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'get_storage': grpc.unary_unary_rpc_method_handler(
          servicer.get_storage,
          request_deserializer=node__listener_dot_grpc_dot_storage__pb2.Request.FromString,
          response_serializer=node__listener_dot_grpc_dot_storage__pb2.Response.SerializeToString,
      ),
      'get_changes': grpc.unary_stream_rpc_method_handler(
          servicer.get_changes,
          request_deserializer=node__listener_dot_grpc_dot_storage__pb2.EmptyRequest.FromString,
          response_serializer=node__listener_dot_grpc_dot_storage__pb2.Response.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Provider', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
